adminUser:
  password: local:wbailey-boot7/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: wbailey@cloudbees.com
  token: local:wbailey-boot7/pipelineUser:token
  username: warrenbailey-cb-bot
prow:
  hmacToken: local:wbailey-boot7/prow:hmacToken
